# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lipstick' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "CollectionKit"
  pod "PINRemoteImage"
  pod "YetAnotherAnimationLibrary"
  pod 'DAOSearchBar', '~> 1.2.5'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'ReactiveCocoa', '~> 7.0'
  pod 'expanding-collection'
  pod 'UIEmptyState'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'FaveButton'
  pod 'SwiftReorder'
  # Pods for Lipstick

  target 'LipstickTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LipstickUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
